import { EmbedBuilder, MessageFlags } from 'discord.js';
import { genAI, TEMP_DIR, checkSummaryRateLimit, incrementSummaryUsage } from '../botManager.js';
import { fetchMessagesForSummary } from '../modules/utils.js';
import path from 'path';
import fs from 'fs/promises';

const SUMMARY_MODEL = 'gemini-2.5-flash';

export const summaryCommand = {
  name: 'summary',
  description: 'Summarize a conversation based on a message link'
};

export async function handleSummaryCommand(interaction) {
  try {
    // 1. Check Rate Limit
    const limitCheck = checkSummaryRateLimit(interaction.user.id);
    if (!limitCheck.allowed) {
      return interaction.reply({
        content: limitCheck.message,
        flags: MessageFlags.Ephemeral
      });
    }

    const link = interaction.options.getString('link');
    const count = interaction.options.getInteger('count') || 50;

    await interaction.deferReply();
    
    const result = await fetchMessagesForSummary(interaction, link, count);

    if (result.error) {
      const errorEmbed = new EmbedBuilder()
        .setColor(0xFF5555)
        .setTitle('❌ Summary Failed')
        .setDescription(result.error);
      return interaction.editReply({ embeds: [errorEmbed] });
    }

    if (!result.success || !result.content) {
      return interaction.editReply({ content: 'Failed to fetch messages for summary.' });
    }

    // Prepare content for AI
    const fileName = `summary_${interaction.id}_${Date.now()}.txt`;
    const filePath = path.join(TEMP_DIR, fileName);
    const fileContent = `Discord Messages Summary Context\nChannel: #${result.channelName}\nServer: ${result.guildName}\nMessages Fetched: ${result.messageCount}\n\n${result.content}`;

    await fs.writeFile(filePath, fileContent);

    // Upload to Gemini
    const uploadResult = await genAI.files.upload({
      file: filePath,
      config: {
        mimeType: 'text/plain',
        displayName: 'Discord Conversation Log'
      }
    });

    await fs.unlink(filePath).catch(() => {});

    // Generate Summary
    const model = genAI.models; 
    
    const prompt = `Please analyze the attached conversation log from Discord.
    
    Provide a clear, structured summary of the discussion.
    - Highlight key topics discussed.
    - Identify active participants.
    - Mention any decisions made or funny moments.
    - Keep the tone helpful and concise.
    
    The log contains approximately ${result.messageCount} messages centered around the provided link.`;

    const request = {
      model: SUMMARY_MODEL,
      contents: [{
        role: 'user',
        parts: [
          { text: prompt },
          {
            fileData: {
              fileUri: uploadResult.uri,
              mimeType: uploadResult.mimeType
            }
          }
        ]
      }]
    };

    const genResult = await genAI.models.generateContent(request);
    const summaryText = genResult.text || "Could not generate summary.";

    const embed = new EmbedBuilder()
      .setColor(0x00FF00)
      .setTitle(`📝 Conversation Summary`)
      .setDescription(summaryText.slice(0, 4096))
      .addFields(
        { name: '📍 Context', value: `[Jump to Start Message](${link})`, inline: true },
        { name: '📊 Messages Analyzed', value: `${result.messageCount}`, inline: true },
        { name: '📂 Channel', value: `#${result.channelName}`, inline: true }
      )
      .setFooter({ text: `Generated by ${interaction.user.displayName}` })
      .setTimestamp();

    await interaction.editReply({ embeds: [embed] });

    // 2. Increment Usage on Success
    incrementSummaryUsage(interaction.user.id);

  } catch (error) {
    console.error('Error in handleSummaryCommand:', error);
    await interaction.editReply({ 
      content: 'An error occurred while generating the summary.' 
    }).catch(() => {});
  }
}
